// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxMfVvHzsbWSwWFL67maORNQ6RUuEyKw',
    appId: '1:677311243873:web:fa6d04de5de8514cfa6c20',
    messagingSenderId: '677311243873',
    projectId: 'esp32-mc',
    authDomain: 'esp32-mc.firebaseapp.com',
    databaseURL: 'https://esp32-mc-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mc.appspot.com',
    measurementId: 'G-068ZPVWGYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhU3LFLPI7K1jg-8Se0uFX6yXlbPBZZcw',
    appId: '1:677311243873:android:6dd1047219714258fa6c20',
    messagingSenderId: '677311243873',
    projectId: 'esp32-mc',
    databaseURL: 'https://esp32-mc-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuh49OmqI6ik-M9ZmFyHYEeIUhKf4xAyQ',
    appId: '1:677311243873:ios:a22ce7c43f01faa0fa6c20',
    messagingSenderId: '677311243873',
    projectId: 'esp32-mc',
    databaseURL: 'https://esp32-mc-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mc.appspot.com',
    iosBundleId: 'com.example.morseCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuh49OmqI6ik-M9ZmFyHYEeIUhKf4xAyQ',
    appId: '1:677311243873:ios:a22ce7c43f01faa0fa6c20',
    messagingSenderId: '677311243873',
    projectId: 'esp32-mc',
    databaseURL: 'https://esp32-mc-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mc.appspot.com',
    iosBundleId: 'com.example.morseCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKxMfVvHzsbWSwWFL67maORNQ6RUuEyKw',
    appId: '1:677311243873:web:d8aa6532f021da5ffa6c20',
    messagingSenderId: '677311243873',
    projectId: 'esp32-mc',
    authDomain: 'esp32-mc.firebaseapp.com',
    databaseURL: 'https://esp32-mc-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mc.appspot.com',
    measurementId: 'G-7RP2JSZE41',
  );

}